#!/usr/bin/env bash

docker run                                                                     \
  --rm                                                                         \
  -e GITHUB_REPO=$GITHUB_REPO                                                  \
  -e GITHUB_USER=$GITHUB_USER                                                  \
  -e GITHUB_BRANCH=$GITHUB_BRANCH                                              \
  -e REPO_DIR=$REPO_DIR                                                        \
  -e DOCKERHUB_USER=$DOCKERHUB_USER                                            \
  -e DOCKERHUB_PASS=$DOCKERHUB_PASS                                            \
  -e TARGET=$TARGET                                                            \
  -v /var/run/docker.sock:/var/run/docker.sock                                 \

  danielo515/containerbuilder
